Config = {}

Config.Objects = {
    ["cone"] = {model = `prop_roadcone02a`, freeze = false},
    ["talt"] = {model = `prop_battle_champ_open_02`, freeze = false},
    ["talt2"] = {model = `prop_battle_champ_open_03`, freeze = false},
    ["talt3"] = {model = `prop_battle_champ_open`, freeze = false},
    ["talt4"] = {model = `prop_battle_champ_closed_02`, freeze = false},
    ["barier"] = {model = `prop_barrier_work05`, freeze = true},
    ["schotten"] = {model = `prop_sign_road_06f`, freeze = true},
    ["tent"] = {model = `prop_gazebo_03`, freeze = false},
    ["light"] = {model = `prop_worklight_03b`, freeze = true},
    ["medic"] = {model = `xm_prop_x17_bag_med_01a`, freeze = true},
}

Config.Locations = {
   ["duty"] = {
       [1] = vector3(-449.811, 6012.909, 31.815-0.5), --Paleto
       [2] = vector3(1852.94, 3689.87, 34.28-0.5), --Sandy
       [3] = vector3(1789.85, 2548.28, 45.8-0.5), -- Fängelset
       [4] = vector3(1792.81, 2598.37, 45.56-0.5), -- Fängelset vid bil
   },
   ["vehicle"] = {
       [1] = vector4(-454.75, 6001.88, 30.95, 86.86), --Paleto
       [2] = vector4(1868.07, 3682.77, 33.66, 216.27), --Sandy
       [3] = vector4(1795.67, 2602.71, 45.82, 269.72), -- Fängelset
   },
   ["stash"] = {
       [1] = vector3(486.43, -995.31, 30.69), --Stan
       [2] = vector3(1850.76, 3694.62, 34.28), --Sandy
       [3] = vector3(1779.73, 2542.35, 45.8), --Fängelse
   },
   ["impound"] = {
       [1] = vector4(463.4, -1019.47, 28.11, 89.52), --Stan
       [2] = vector4(-468.78, 6038.77, 30.93, 43.91), --Paleto 
   },
   ["helicopter"] = {
       [1] = vector4(449.168, -981.325, 43.691, 87.234), --Stan
       [2] = vector4(-475.43, 5988.353, 31.716, 31.34), --Paleto
   },
   ["armory"] = {
       [1] = vector3(482.54, -995.16, 30.69), --Stan
       [2] = vector3(1849.26, 3695.17, 34.28), --Sandy
       [3] = vector3(1777.35, 2543.55, 45.8), --Fängelse
   },
   ["trash"] = {
       [1] = vector3(457.68, -1002.59, 27.49), --Stan
       [2] = vector3(1853.22, 3694.49, 34.28), --Sandy
   },
   ["fingerprint"] = {
       [1] = vector3(484.27, -987.96, 30.69), --Stan
   },
   ["evidence"] = {
       [1] = vector3(474.91, -994.09, 26.27), --Stan
       [2] = vector3(1842.39, 3691.32, 34.28), --Sandy
   },
   ["evidence2"] = {
       [1] = vector3(472.73, -994.43, 26.27), --stan
       [2] = vector3(1836.06, 3679.62, 34.28), --Sandy
   },
   ["evidence3"] = {
       [1] = vector3(1779.03, 2546.41, 45.8), --FÄngelset
   },
   ["stations"] = {
       [1] = {label = "Polisstation", coords = vector3(443.02, -982.23, 30.72)},
       [2] = {label = "Fängelse", coords = vector3(1845.903, 2585.873, 45.672)},
       [3] = {label = "Polisstation Paleto", coords = vector3(-451.55, 6014.25, 31.716)},
       [4] = {label = "Polisstation Sandy", coords = vector3(1850.76, 3694.62, 34.28)},
   },
}

Config.ArmoryWhitelist = {}

Config.Helicopter = "POLMAV"

Config.SecurityCameras = {
    hideradar = false,
    cameras = {
        [1] = {label = "Pacific Bank CAM#1", coords = vector3(257.45, 210.07, 109.08), r = {x = -25.0, y = 0.0, z = 28.05}, canRotate = false, isOnline = true},
        [2] = {label = "Pacific Bank CAM#2", coords = vector3(232.86, 221.46, 107.83), r = {x = -25.0, y = 0.0, z = -140.91}, canRotate = false, isOnline = true},
        [3] = {label = "Pacific Bank CAM#3", coords = vector3(252.27, 225.52, 103.99), r = {x = -35.0, y = 0.0, z = -74.87}, canRotate = false, isOnline = true},
        [4] = {label = "Limited Ltd Grove St. CAM#1", coords = vector3(-53.1433, -1746.714, 31.546), r = {x = -35.0, y = 0.0, z = -168.9182}, canRotate = false, isOnline = true},
        [5] = {label = "Rob's Liqour Prosperity St. CAM#1", coords = vector3(-1482.9, -380.463, 42.363), r = {x = -35.0, y = 0.0, z = 79.53281}, canRotate = false, isOnline = true},
        [6] = {label = "Rob's Liqour San Andreas Ave. CAM#1", coords = vector3(-1224.874, -911.094, 14.401), r = {x = -35.0, y = 0.0, z = -6.778894}, canRotate = false, isOnline = true},
        [7] = {label = "Limited Ltd Ginger St. CAM#1", coords = vector3(-718.153, -909.211, 21.49), r = {x = -35.0, y = 0.0, z = -137.1431}, canRotate = false, isOnline = true},
        [8] = {label = "24/7 Supermarkt Innocence Blvd. CAM#1", coords = vector3(23.885, -1342.441, 31.672), r = {x = -35.0, y = 0.0, z = -142.9191}, canRotate = false, isOnline = true},
        [9] = {label = "Rob's Liqour El Rancho Blvd. CAM#1", coords = vector3(1133.024, -978.712, 48.515), r = {x = -35.0, y = 0.0, z = -137.302}, canRotate = false, isOnline = true},
        [10] = {label = "Limited Ltd West Mirror Drive CAM#1", coords = vector3(1151.93, -320.389, 71.33), r = {x = -35.0, y = 0.0, z = -119.4468}, canRotate = false, isOnline = true},
        [11] = {label = "24/7 Supermarkt Clinton Ave CAM#1", coords = vector3(383.402, 328.915, 105.541), r = {x = -35.0, y = 0.0, z = 118.585}, canRotate = false, isOnline = true},
        [12] = {label = "Limited Ltd Banham Canyon Dr CAM#1", coords = vector3(-1832.057, 789.389, 140.436), r = {x = -35.0, y = 0.0, z = -91.481}, canRotate = false, isOnline = true},
        [13] = {label = "Rob's Liqour Great Ocean Hwy CAM#1", coords = vector3(-2966.15, 387.067, 17.393), r = {x = -35.0, y = 0.0, z = 32.92229}, canRotate = false, isOnline = true},
        [14] = {label = "24/7 Supermarkt Ineseno Road CAM#1", coords = vector3(-3046.749, 592.491, 9.808), r = {x = -35.0, y = 0.0, z = -116.673}, canRotate = false, isOnline = true},
        [15] = {label = "24/7 Supermarkt Barbareno Rd. CAM#1", coords = vector3(-3246.489, 1010.408, 14.705), r = {x = -35.0, y = 0.0, z = -135.2151}, canRotate = false, isOnline = true},
        [16] = {label = "24/7 Supermarkt Route 68 CAM#1", coords = vector3(539.773, 2664.904, 44.056), r = {x = -35.0, y = 0.0, z = -42.947}, canRotate = false, isOnline = true},
        [17] = {label = "Rob's Liqour Route 68 CAM#1", coords = vector3(1169.855, 2711.493, 40.432), r = {x = -35.0, y = 0.0, z = 127.17}, canRotate = false, isOnline = true},
        [18] = {label = "24/7 Supermarkt Senora Fwy CAM#1", coords = vector3(2673.579, 3281.265, 57.541), r = {x = -35.0, y = 0.0, z = -80.242}, canRotate = false, isOnline = true},
        [19] = {label = "24/7 Supermarkt Alhambra Dr. CAM#1", coords = vector3(1966.24, 3749.545, 34.143), r = {x = -35.0, y = 0.0, z = 163.065}, canRotate = false, isOnline = true},
        [20] = {label = "24/7 Supermarkt Senora Fwy CAM#2", coords = vector3(1729.522, 6419.87, 37.262), r = {x = -35.0, y = 0.0, z = -160.089}, canRotate = false, isOnline = true},
        [21] = {label = "Fleeca Bank Hawick Ave CAM#1", coords = vector3(309.341, -281.439, 55.88), r = {x = -35.0, y = 0.0, z = -146.1595}, canRotate = false, isOnline = true},
        [22] = {label = "Fleeca Bank Legion Square CAM#1", coords = vector3(144.871, -1043.044, 31.017), r = {x = -35.0, y = 0.0, z = -143.9796}, canRotate = false, isOnline = true},
        [23] = {label = "Fleeca Bank Hawick Ave CAM#2", coords = vector3(-355.7643, -52.506, 50.746), r = {x = -35.0, y = 0.0, z = -143.8711}, canRotate = false, isOnline = true},
        [24] = {label = "Fleeca Bank Del Perro Blvd CAM#1", coords = vector3(-1214.226, -335.86, 39.515), r = {x = -35.0, y = 0.0, z = -97.862}, canRotate = false, isOnline = true},
        [25] = {label = "Fleeca Bank Great Ocean Hwy CAM#1", coords = vector3(-2958.885, 478.983, 17.406), r = {x = -35.0, y = 0.0, z = -34.69595}, canRotate = false, isOnline = true},
        [26] = {label = "Paleto Bank CAM#1", coords = vector3(-102.939, 6467.668, 33.424), r = {x = -35.0, y = 0.0, z = 24.66}, canRotate = false, isOnline = true},
        [27] = {label = "Del Vecchio Liquor Paleto Bay", coords = vector3(-163.75, 6323.45, 33.424), r = {x = -35.0, y = 0.0, z = 260.00}, canRotate = false, isOnline = true},
        [28] = {label = "Don's Country Store Paleto Bay CAM#1", coords = vector3(166.42, 6634.4, 33.69), r = {x = -35.0, y = 0.0, z = 32.00}, canRotate = false, isOnline = true},
        [29] = {label = "Don's Country Store Paleto Bay CAM#2", coords = vector3(163.74, 6644.34, 33.69), r = {x = -35.0, y = 0.0, z = 168.00}, canRotate = false, isOnline = true},
        [30] = {label = "Don's Country Store Paleto Bay CAM#3", coords = vector3(169.54, 6640.89, 33.69), r = {x = -35.0, y = 0.0, z = 5.78}, canRotate = false, isOnline = true},
        [31] = {label = "Vangelico Jewelery CAM#1", coords = vector3(-627.54, -239.74, 40.33), r = {x = -35.0, y = 0.0, z = 5.78}, canRotate = true, isOnline = true},
        [32] = {label = "Vangelico Jewelery CAM#2", coords = vector3(-627.51, -229.51, 40.24), r = {x = -35.0, y = 0.0, z = -95.78}, canRotate = true, isOnline = true},
        [33] = {label = "Vangelico Jewelery CAM#3", coords = vector3(-620.3, -224.31, 40.23), r = {x = -35.0, y = 0.0, z = 165.78}, canRotate = true, isOnline = true},
        [34] = {label = "Vangelico Jewelery CAM#4", coords = vector3(-622.57, -236.3, 40.31), r = {x = -35.0, y = 0.0, z = 5.78}, canRotate = true, isOnline = true},
        [35] = {label = "Fängelse Kamera 1", coords = vector3(1779.75, 2588.51, 50.8), r = {x = 0.0, y = 0.0, z = 0.78}, canRotate = true, isOnline = true}, --Limpan
        [36] = {label = "Fängelse Kamera 1 Ute innergård", coords = vector3(1710.99, 2538.73, 55.56), r = {x = -35.0, y = 0.0, z = 10.78}, canRotate = true, isOnline = true}, --Limpan
        [37] = {label = "Fängelse Kamera 2 Ute Entre", coords = vector3(1835.3, 2602.88, 51.84), r = {x = 0.0, y = 0.0, z = 0.78}, canRotate = true, isOnline = true}, --Limpan
    },
}

Config.AuthorizedVehicles = {
	-- Grade 0
	[0] = {
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police76"]= "Volvo XC60" ,
	},

	-- Grade 1
	[1] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police76"]= "Volvo XC60" ,
	},
	-- Grade 2
	[2] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
	-- Grade 3
	[3] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
	-- Grade 4
	[4] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
    [5] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
    [6] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
    [7] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
    [8] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
    [9] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
    [10] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
    [11] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
    [12] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
    [13] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	},
    [14] = {
		["police80"]= "Ford - Insatsledning" ,
		["police30"]= "Volkswagen Kombi - Insatsledning" ,
		["police43"]= "Mercedes Sprinter - Kravall" ,
		["police62"]= "Volkswagen T6 Caravelle - Trafik" ,
		["police31"]= "Volkswagen T6 Caravelle - Sjöpolisen" ,
		["police53"]= "Volkswagen T6 Caravelle - Polisutbildning" ,
		["police66"]= "Volkswagen T6 Caravelle - Områdespolis" ,
		["police37"]= "Volvo V90CC - Trafik" ,
		["police22"]= "Volvo V90CC - Polisutbildning" ,
		["police74"]= "Volkswagen Tiguan - Trafik" ,
		["police61"]= "Volkswagen Kombi - Trafik" ,
		["police68"]= "Volkswagen Amarok - Hund" ,
		["police2"]= "Volvo V90 - Trafik" ,
		["police69"]= "Volkswagen T6 Kombi Dubbla Whelen - Trafik" ,
		["police15"]= "Volvo XC70 - Trafik" ,
		["police23"]= "Volvo XC70 - Airport Polis" ,
		["police34"]= "Volkswagen Passat B7 Alltrack  - Trafik" ,
		["police"]= "Volvo V70 - Trafik" ,
		["police8"]= "Volkswagen T5 Caravelle W1 & Rotorljus" ,
		["police36"]= "Mercedes-Benz E-Klass - Trafik" ,
		["police70"]= "Volvo XC70 - Yttrebefäl" ,
		["police65"]= "Volkswagen Kombi - Yttre Befäl" ,
		["police29"]= "Volkswagen Tiguan - Yttre Befäl" ,
		["police20"]= "Volvo V90CC - Yttrebefäl" ,
		["police58"]= "Volkswagen T6 Caravelle - Yttre Befäl" ,
		["police42"]= "Mercedes-Benz E-Klass - Civil" ,
		["police71"]= "Volkswagen T5 Kombi - Civil" ,
		["police72"]= "Volkswagen T5 Kombi - Civil FRI" ,
		["police27"]= "Audi A5 - Civil" ,
		["police24"]= "Volvo V70 - Civil" ,
		["police48"]= "Volkswagen Passat B7 Alltrack - Civil" ,
		["police5"]= "Volvo XC70 - Civil Röd" ,
		["police77"]= "Volvo XC70 - Civil Svart" ,
		["police12"]= "Volvo V90 - Civil" ,
		["police41"]= "Volkswagen Amarok - Civil" ,
		["police73"]= "Volkswagen Tiguan - Civil" ,
		["police45"]= "Volvo V90CC - Civil Svart" ,
		["police59"]= "Volvo V90CC - Civil Vit" ,
		["police64"]= "Volkswagen T6 Caravelle - Civil" ,
		["police44"]= "Toyoya Landcruiser - FRI",
		["police76"]= "Volvo XC60" ,
	}
}

Config.WhitelistedVehicles = {}

Config.AmmoLabels = {
    ["AMMO_PISTOL"] = "9x19mm Pistolhylsa",
    ["AMMO_SMG"] = "9x19mm SMGhylsa",
    ["AMMO_RIFLE"] = "7.62x39mm hylsa",
    ["AMMO_MG"] = "7.92x57mm mauser bullet",
    ["AMMO_SHOTGUN"] = "12-gauge hylsa",
    ["AMMO_SNIPER"] = "Grovkalibrig hylsa",
}

Config.Radars = {
	vector4(-623.44421386719, -823.08361816406, 25.25704574585, 145.0),
	vector4(-652.44421386719, -854.08361816406, 24.55704574585, 325.0),
	vector4(1623.0114746094, 1068.9924316406, 80.903594970703, 84.0),
	vector4(-2604.8994140625, 2996.3391113281, 27.528566360474, 175.0),
	vector4(2136.65234375, -591.81469726563, 94.272926330566, 318.0),
	vector4(2117.5764160156, -558.51013183594, 95.683128356934, 158.0),
	vector4(406.89505004883, -969.06286621094, 29.436267852783, 33.0),
	vector4(657.315, -218.819, 44.06, 320.0),
	vector4(2118.287, 6040.027, 50.928, 172.0),
	vector4(-106.304, -1127.5530, 30.778, 230.0),
	vector4(-823.3688, -1146.980, 8.0, 300.0),
}

Config.CarItems = {
    [1] = {
        name = "heavyarmor",
        amount = 2,
        info = {},
        type = "item",
        slot = 1,
    },
    [2] = {
        name = "empty_evidence_bag",
        amount = 10,
        info = {},
        type = "item",
        slot = 2,
    },
    [3] = {
        name = "police_stormram",
        amount = 1,
        info = {},
        type = "item",
        slot = 3,
    },
    [4] = {
        name = "bandage",
        amount = 10,
        info = {},
        type = "item",
        slot = 4,
    },
    [5] = {
        name = "painkillers",
        amount = 10,
        info = {},
        type = "item",
        slot = 5,
    },
}

Config.Items = {
    label = "Polismyndighetens Vapenskåp",
    slots = 30,
    items = {

        [1] = {
            name = "weapon_stungun",
            price = 0,
            amount = 1,
            info = {
                serie = "",            
            },
            type = "weapon",
            slot = 1,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },

        [2] = {
            name = "weapon_nightstick",
            price = 0,
            amount = 1,
            info = {},
            type = "weapon",
            slot = 2,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        
        [3] = {
            name = "handcuffs",
            price = 0,
            amount = 1,
            info = {},
            type = "item",
            slot = 3,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [4] = {
            name = "weapon_flashlight",
            price = 0,
            amount = 1,
            info = {},
            type = "weapon",
            slot = 4,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [5] = {
            name = "empty_evidence_bag",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 5,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [6] = {
            name = "police_stormram",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 6,
            authorizedJobGrades = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [7] = {
            name = "armor",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 7,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [8] = {
            name = "radio",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 8,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [9] = {
            name = "heavyarmor",
            price = 0,
            amount = 50,
            info = {},
            type = "item",
            slot = 9,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [10] = {
            name = "specialbadge",
            price = 0,
            amount = 1,
            info = {},
            type = "item",
            slot = 10,
            authorizedJobGrades = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [11] = {
            name = "pistol_ammo",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 11,
            authorizedJobGrades = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [12] = {
            name = "weapon_combatpistol",
            price = 0,
            amount = 1,
            info = {},
            type = "weapon",
            slot = 12,
            authorizedJobGrades = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [13] = {
            name = "smg_ammo",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 13,
            authorizedJobGrades = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [14] = {
            name = "shotgun_ammo",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 14,
            authorizedJobGrades = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [15] = {
            name = "rifle_ammo",
            price = 0,
            amount = 5,
            info = {},
            type = "item",
            slot = 15,
            authorizedJobGrades = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [16] = {
            name = "weapon_pumpshotgun",
            price = 0,
            amount = 1,
            info = {
                serie = "",
                attachments = {
                    {component = "COMPONENT_AT_AR_FLSH", label = "Ficklampa"},
                }
            },
            type = "weapon",
            slot = 16,
            authorizedJobGrades = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [17] = {
            name = "weapon_smg",
            price = 0,
            amount = 1,
            info = {
                serie = "",                
                attachments = {
                    {component = "COMPONENT_AT_SCOPE_MACRO_02", label = "1x Sikte"},
                    {component = "COMPONENT_AT_AR_FLSH", label = "Ficklampa"},
                }
            },
            type = "weapon",
            slot = 17,
            authorizedJobGrades = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [18] = {
            name = "weapon_carbinerifle",
            price = 0,
            amount = 1,
            info = {
                serie = "",
                attachments = {
                    {component = "COMPONENT_AT_AR_FLSH", label = "Ficklampa"},
                    {component = "COMPONENT_AT_SCOPE_MEDIUM", label = "3x Sikte"},
                }
            },
            type = "weapon",
            slot = 18,
            authorizedJobGrades = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14}
        },
        [19] = {
            name = "weaponlicense",
            price = 0,
            amount = 1,
            info = {},
            type = "item",
            slot = 19,
            authorizedJobGrades = {10, 11, 12, 13 ,14}
        },
    }
}
